apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-logger
  annotations:
    github.com/project-slug: coopnorge/go-logger
spec:
  type: other
  lifecycle: unknown
  owner: engineering
